### ISSUE TITLE
How to watch the bot play from first-person perspective?

### ISSUE THREAD

**Issue by taoisu** [MineDojo/Voyager#19]
Hi I'm new to the Minecraft world, I saw the videos of bot playing but when I was doing it I'm just a player in the same world with the bot, anyone help me understand how to watch bot play?

**Comment by xieleo5** [comment]
Hi, thanks for your interest in this project. Due to Mineflayer's limitation, we currently can not directly get the bot's view in the game. Although there's a plugin called [prismarine-viewer](https://github.com/PrismarineJS/prismarine-viewer), the video quality is not good enough so we didn't use it.  The video of our demo is generated by [replay-mod](https://www.replaymod.com/). We start the recording and let the bot play for hours, then come back to the recording and render the view from the bot.

**Comment by taoisu** [comment]
Thanks for the explanation, this is helpful!

**Comment by go-maple** [comment]
@xieleo5 bro,Can you create a channel in Discord,Let us to talk about Voyager?

**Comment by dravolin** [comment]
simply use the spectator mode:
```
/gamemode spectator
/spectate bot
```
