### ISSUE TITLE
Items not being added to inventory

### ISSUE THREAD

**Issue by JesseRWeigel** [MineDojo/Voyager#40]
It seems like the bot is not recognizing items in it's inventory. I see it mining but the console output does not register the new items. 

Is this a known issue? Would could be causing it? I am trying to go through the code to see what the issue might be but I haven't found anything so far.

**Comment by JesseRWeigel** [comment]
I noticed the note about this in the new F.A.Q. section. I increased the `env_wait_ticks` to `40`. This caused a noticeable delay between actions but does not solve the inventory issue. Has anyone had any luck with this? If so, what did you set `env_wait_ticks` to?

**Comment by xieleo5** [comment]
Hi, could you elaborate more about what the bot is mining? The asynchrony of inventory happens mostly due to the command we use to recycle the crafting table and furnace. Normal mining should not cause this problem. Other reasons may cause this problem, such as certain blocks not yielding any items or the bot encountering difficulties in picking up items.

In Voyager's experiments, we configured `env_wait_ticks=20`. This setting may also be influenced by the speed of your PC. Our experiments primarily use a gaming Windows 11 PC. You can choose an appropriate value depending on your situation.

**Comment by theblazehen** [comment]
I'm observing the same issue, with wood

**Comment by theblazehen** [comment]
Following https://github.com/MineDojo/Voyager/issues/25#issuecomment-1567237266, make sure the game mode is set to survival, difficulty to peaceful. This is contrary to what the documentation states if I'm reading it correctly

**Comment by Benjamin-eecs** [comment]
> Following [#25 (comment)](https://github.com/MineDojo/Voyager/issues/25#issuecomment-1567237266), make sure the game mode is set to survival, difficulty to peaceful. This is contrary to what the documentation states if I'm reading it correctly

I have tested it, it is true, if the game mode is set to creative, then the inventory will always be empty. The game mode must be set to survival.

cc @xieleo5

**Comment by JesseRWeigel** [comment]
Should the documentation be updated for this? If so I can create a PR for it.
